PRAGMA foreign_keys = 0;

CREATE TABLE sqlitestudio_temp_table AS SELECT *
                                          FROM descriptions;

DROP TABLE descriptions;

CREATE TABLE descriptions (
    --rowid                         --auto generated by sqlite, can be queried
    Id            TEXT PRIMARY KEY  --The GUID from Brahms database
                       UNIQUE,
    CalcFullName  TEXT,             --The Scientificname from Brahms
    TextTitle     TEXT,             --("Morphology", "Diagnostic", "Distribution", "Habitat") type of Text
    CoalescedText TEXT,             --The original TaxonText or the Translation by Gemini AI if original not English
    FinalText     TEXT,             --The FinalText as edited by Gemini AI, to be edited/reviewed in FloraReview
    Reviewer      TEXT,             --The last User who saved/approved/re-opened ApprovedText
    Status        TEXT,             --The status of ApprovedText ("open": can be edited,"close": approved), can be re-opened if "close".
    Comment       TEXT,             --Comments log when approved, or re-opened
    ApprovedText  TEXT              --The text as saved/approved by the User
);

INSERT INTO descriptions (
                             Id,
                             CalcFullName,
                             TextTitle,
                             CoalescedText,
                             FinalText,
                             Reviewer,
                             Status,
                             Comment,
                             ApprovedText
                         )
                         SELECT Id,
                                CalcFullName,
                                TextTitle,
                                CoalescedText,
                                FinalText,
                                Reviewer,
                                Status,
                                Comment,
                                ApprovedText
                           FROM sqlitestudio_temp_table;

DROP TABLE sqlitestudio_temp_table;

CREATE INDEX TextTitle ON descriptions (
    TextTitle
);

CREATE INDEX Status ON descriptions (
    Status
);

CREATE INDEX Reviewer ON descriptions (
    Reviewer
);

CREATE INDEX Id ON descriptions (
    Id
);

CREATE INDEX CalcFullName ON descriptions (
    CalcFullName
);

PRAGMA foreign_keys = 1;
